# -*- coding: utf-8 -*-
#
# This file is part of xrootdpyfs
# Copyright (C) 2015-2020 CERN.
#
# xrootdpyfs is free software; you can redistribute it and/or modify it under
# the terms of the Revised BSD License; see LICENSE file for more details.

notifications:
  email: false

language: python

python:
  - "3.6"

services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - env: XROOTD_VERSION=''

env:
  - XROOTD_VERSION=4.8.5
  - XROOTD_VERSION=4.9.1
  - XROOTD_VERSION=4.11.2
  - XROOTD_VERSION=''

cache:
  - docker

install:
  - "docker build -t xrootd --build-arg xrootd_version=${XROOTD_VERSION} ."

script:
  - "docker run -h xrootdpyfs -t xrootd"

after_success:
  - coveralls
